import { Poppins } from 'next/font/google';
import "../../../globals.css";
import { Metadata } from 'next';
import { getUser } from '@/lib/auth';
import { redirect } from 'next/navigation';

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const { session,user } = await getUser()

  if (session && user.role !== 'superadmin') {
    return redirect('/dashboard')
  }

  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
